// <auto-generated />
using System;
using CoreMDFe.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreMDFe.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260227010722_UpdateSchemaMDFeRodoviarioCompleto")]
    partial class UpdateSchemaMDFeRodoviarioCompleto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("CoreMDFe.Core.Entities.Condutor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Condutores");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ConfiguracaoApp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CaminhoArquivoCertificado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiretorioSalvarPdf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DiretorioSalvarXml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("GerarQrCode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSalvarXml")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Logomarca")
                        .HasColumnType("BLOB");

                    b.Property<bool>("ManterCertificadoEmCache")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModalidadePadrao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RespTecCnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("RespTecEmail")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("RespTecNome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("RespTecTelefone")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaCertificado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Serie")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeOut")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(5000);

                    b.Property<int>("TipoAmbiente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoEmissaoPadrao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoEmitentePadrao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoTransportadorPadrao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UfEmitente")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<long>("UltimaNumeracao")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId")
                        .IsUnique();

                    b.ToTable("Configuracoes");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<long>("CodigoIbgeMunicipio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("InscricaoEstadual")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeMunicipio")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("RNTRC")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiglaUf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ManifestoAutorizadoDownload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ManifestoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManifestoId");

                    b.ToTable("ManifestoAutorizadosDownload");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ManifestoCiot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ciot")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ManifestoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManifestoId");

                    b.ToTable("ManifestoCiots");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ManifestoCondutor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CondutorBaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ManifestoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManifestoId");

                    b.ToTable("ManifestoCondutores");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ManifestoContratante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ManifestoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManifestoId");

                    b.ToTable("ManifestoContratantes");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ManifestoDocumentoFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChaveAcesso")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IndicadorReentrega")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MunicipioDescarregamentoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SegundoCodigoBarra")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioDescarregamentoId");

                    b.ToTable("ManifestoDocumentosFiscais");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ManifestoEletronico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChaveAcesso")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoStatus")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("CodigoUnidadePeso")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHoraInicioViagem")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IndicadorCarregamentoPosterior")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InformacoesComplementares")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("InformacoesFisco")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Modalidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Modelo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotivoStatus")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PesoTotalCarga")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProdutoEAN")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProdutoNCM")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProdutoNome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProdutoTipoCarga")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtocoloAutorizacao")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtocoloCancelamento")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtocoloEncerramento")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<int>("QtdCTe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QtdMDFe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QtdNFe")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Recibo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReciboAutorizacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReciboCancelamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReciboEncerramento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Serie")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoAmbiente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoEmissao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoEmitente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoTransportador")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UfDestino")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("UfOrigem")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorTotalCarga")
                        .HasColumnType("TEXT");

                    b.Property<string>("XmlAssinado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Manifestos");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ManifestoMunicipioCarregamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CodigoIbge")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ManifestoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeMunicipio")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManifestoId");

                    b.ToTable("ManifestoMunicipiosCarregamento");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ManifestoMunicipioDescarregamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CodigoIbge")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ManifestoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeMunicipio")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManifestoId");

                    b.ToTable("ManifestoMunicipiosDescarregamento");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ManifestoPagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChavePix")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("CnpjInstituicaoPagamento")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("CpfCnpjContratante")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("IndicadorPagamento")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ManifestoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeContratante")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorAdiantamento")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorTotalViagem")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManifestoId");

                    b.ToTable("ManifestoPagamentos");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ManifestoPercurso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ManifestoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManifestoId");

                    b.ToTable("ManifestoPercursos");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ManifestoSeguro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CnpjSeguradora")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("CpfCnpjResponsavel")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ManifestoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeSeguradora")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroApolice")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroAverbacao")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Responsavel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ManifestoId");

                    b.ToTable("ManifestoSeguros");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ManifestoValePedagio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CnpjFornecedor")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("CpfCnpjPagador")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ManifestoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroCompra")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManifestoId");

                    b.ToTable("ManifestoValesPedagio");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ManifestoVeiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CapacidadeKg")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacidadeM3")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ManifestoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropCpfCnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropIE")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropNome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropRNTRC")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int>("PropTipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PropUF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Renavam")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<int>("TaraKg")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoCarroceria")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoRodado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("UfLicenciamento")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VeiculoBaseId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManifestoId");

                    b.ToTable("ManifestoVeiculos");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CapacidadeKg")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacidadeM3")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProprietarioCpfCnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProprietarioIE")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProprietarioNome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProprietarioRNTRC")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProprietarioTipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProprietarioUF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Renavam")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<int>("TaraKg")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoCarroceria")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoRodado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoVeiculo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UfLicenciamento")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ConfiguracaoApp", b =>
                {
                    b.HasOne("CoreMDFe.Core.Entities.Empresa", "Empresa")
                        .WithOne("Configuracao")
                        .HasForeignKey("CoreMDFe.Core.Entities.ConfiguracaoApp", "EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ManifestoAutorizadoDownload", b =>
                {
                    b.HasOne("CoreMDFe.Core.Entities.ManifestoEletronico", "Manifesto")
                        .WithMany("AutorizadosDownload")
                        .HasForeignKey("ManifestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manifesto");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ManifestoCiot", b =>
                {
                    b.HasOne("CoreMDFe.Core.Entities.ManifestoEletronico", "Manifesto")
                        .WithMany("Ciots")
                        .HasForeignKey("ManifestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manifesto");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ManifestoCondutor", b =>
                {
                    b.HasOne("CoreMDFe.Core.Entities.ManifestoEletronico", "Manifesto")
                        .WithMany("Condutores")
                        .HasForeignKey("ManifestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manifesto");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ManifestoContratante", b =>
                {
                    b.HasOne("CoreMDFe.Core.Entities.ManifestoEletronico", "Manifesto")
                        .WithMany("Contratantes")
                        .HasForeignKey("ManifestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manifesto");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ManifestoDocumentoFiscal", b =>
                {
                    b.HasOne("CoreMDFe.Core.Entities.ManifestoMunicipioDescarregamento", "Municipio")
                        .WithMany("Documentos")
                        .HasForeignKey("MunicipioDescarregamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ManifestoEletronico", b =>
                {
                    b.HasOne("CoreMDFe.Core.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ManifestoMunicipioCarregamento", b =>
                {
                    b.HasOne("CoreMDFe.Core.Entities.ManifestoEletronico", "Manifesto")
                        .WithMany("MunicipiosCarregamento")
                        .HasForeignKey("ManifestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manifesto");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ManifestoMunicipioDescarregamento", b =>
                {
                    b.HasOne("CoreMDFe.Core.Entities.ManifestoEletronico", "Manifesto")
                        .WithMany("MunicipiosDescarregamento")
                        .HasForeignKey("ManifestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manifesto");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ManifestoPagamento", b =>
                {
                    b.HasOne("CoreMDFe.Core.Entities.ManifestoEletronico", "Manifesto")
                        .WithMany("Pagamentos")
                        .HasForeignKey("ManifestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manifesto");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ManifestoPercurso", b =>
                {
                    b.HasOne("CoreMDFe.Core.Entities.ManifestoEletronico", "Manifesto")
                        .WithMany("Percursos")
                        .HasForeignKey("ManifestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manifesto");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ManifestoSeguro", b =>
                {
                    b.HasOne("CoreMDFe.Core.Entities.ManifestoEletronico", "Manifesto")
                        .WithMany("Seguros")
                        .HasForeignKey("ManifestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manifesto");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ManifestoValePedagio", b =>
                {
                    b.HasOne("CoreMDFe.Core.Entities.ManifestoEletronico", "Manifesto")
                        .WithMany("ValesPedagio")
                        .HasForeignKey("ManifestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manifesto");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ManifestoVeiculo", b =>
                {
                    b.HasOne("CoreMDFe.Core.Entities.ManifestoEletronico", "Manifesto")
                        .WithMany("Veiculos")
                        .HasForeignKey("ManifestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manifesto");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.Empresa", b =>
                {
                    b.Navigation("Configuracao");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ManifestoEletronico", b =>
                {
                    b.Navigation("AutorizadosDownload");

                    b.Navigation("Ciots");

                    b.Navigation("Condutores");

                    b.Navigation("Contratantes");

                    b.Navigation("MunicipiosCarregamento");

                    b.Navigation("MunicipiosDescarregamento");

                    b.Navigation("Pagamentos");

                    b.Navigation("Percursos");

                    b.Navigation("Seguros");

                    b.Navigation("ValesPedagio");

                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("CoreMDFe.Core.Entities.ManifestoMunicipioDescarregamento", b =>
                {
                    b.Navigation("Documentos");
                });
#pragma warning restore 612, 618
        }
    }
}
